#!/bin/bash
echo "Current directory:"
pwd

echo "List files:"
ls

echo "Create directory"
mkdir testdir

echo "Create file"
touch testfile.txt

echo "Display file content"
echo "Hello Linux" > testfile.txt
cat testfile.txt

echo "Remove file and directory"
rm testfile.txt
rmdir testdir
