#!/bin/bash
echo "Enter two numbers:"
read a b

echo "Addition: $((a+b))"
echo "Subtraction: $((a-b))"
echo "Multiplication: $((a*b))"
echo "Division: $((a/b))"


#!/bin/bash
echo "Enter year:"
read y

if [ $((y%4)) -eq 0 ] && [ $((y%100)) -ne 0 ] || [ $((y%400)) -eq 0 ]
then
  echo "Leap Year"
else
  echo "Not a Leap Year"
fi
